"""add content_type column v4

Revision ID: 04aa8ed15569
Revises: 965b684b7662
Create Date: 2024-05-06 22:44:56.834373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04aa8ed15569"
down_revision: Union[str, None] = "965b684b7662"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_messages", sa.Column("filename", sa.String(), nullable=True)
    )
    op.add_column(
        "business_messages",
        sa.Column("content_type", sa.String(), nullable=True),
    )
    op.drop_column("business_messages", "iteraion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_messages",
        sa.Column("iteraion", sa.INTEGER(), nullable=False),
    )
    op.drop_column("business_messages", "content_type")
    op.drop_column("business_messages", "filename")
    # ### end Alembic commands ###
